---
- name: Zsh for Users
  hosts: all
  tasks:
    - name: Get Oh-My-Zsh installer
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ./install_ohmyzsh.sh
    - name: Set Oh-My-Zsh installer permissions
      file:
        path: ./install_ohmyzsh.sh
        mode: 0755
    - name: Install Oh-My-Zsh
      shell: |
        ./install_ohmyzsh.sh
        sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="jonathan"/' .zshrc
        sed -i 's/plugins=(git)/plugins=(fzf git zsh-interactive-cd)/' .zshrc
        echo '' >> .zshrc
        echo 'export EDITOR="vim"' >> .zshrc
    - name: Delete Oh-My-Zsh installer
      file:
        path: ./install_ohmyzsh.sh
        state: absent
    - name: Delete previous configuration
      file:
        path: ./.zshrc.pre-oh-my-zsh
        state: absent
    - name: Change shell
      user:
        name: user
        shell: /bin/zsh
